name: Cancel PR build(s)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  cancel:
    name: Cancel Build(s)
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Build(s)
      uses: styfle/cancel-workflow-action@0.7.0
      if: "github.ref != 'refs/heads/main'"
      with:
        access_token: ${{ github.token }}
