# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nidevice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enidevice.proto\x12\rnidevice_grpc\"2\n\x0fNIComplexNumber\x12\x0c\n\x04real\x18\x01 \x01(\x01\x12\x11\n\timaginary\x18\x02 \x01(\x01\"5\n\x12NIComplexNumberF32\x12\x0c\n\x04real\x18\x01 \x01(\x02\x12\x11\n\timaginary\x18\x02 \x01(\x02\"/\n\x0cNIComplexI16\x12\x0c\n\x04real\x18\x01 \x01(\x11\x12\x11\n\timaginary\x18\x02 \x01(\x11\"r\n\x0fSmtSpectrumInfo\x12\x15\n\rspectrum_type\x18\x01 \x01(\r\x12\x11\n\tlinear_db\x18\x02 \x01(\r\x12\x0e\n\x06window\x18\x03 \x01(\r\x12\x13\n\x0bwindow_size\x18\x04 \x01(\x11\x12\x10\n\x08\x66\x66t_size\x18\x05 \x01(\x11\x42\x42\n\x12\x63om.ni.grpc.deviceB\x08NiDeviceP\x01\xaa\x02\x1fNationalInstruments.Grpc.Deviceb\x06proto3')



_NICOMPLEXNUMBER = DESCRIPTOR.message_types_by_name['NIComplexNumber']
_NICOMPLEXNUMBERF32 = DESCRIPTOR.message_types_by_name['NIComplexNumberF32']
_NICOMPLEXI16 = DESCRIPTOR.message_types_by_name['NIComplexI16']
_SMTSPECTRUMINFO = DESCRIPTOR.message_types_by_name['SmtSpectrumInfo']
NIComplexNumber = _reflection.GeneratedProtocolMessageType('NIComplexNumber', (_message.Message,), {
  'DESCRIPTOR' : _NICOMPLEXNUMBER,
  '__module__' : 'nidevice_pb2'
  # @@protoc_insertion_point(class_scope:nidevice_grpc.NIComplexNumber)
  })
_sym_db.RegisterMessage(NIComplexNumber)

NIComplexNumberF32 = _reflection.GeneratedProtocolMessageType('NIComplexNumberF32', (_message.Message,), {
  'DESCRIPTOR' : _NICOMPLEXNUMBERF32,
  '__module__' : 'nidevice_pb2'
  # @@protoc_insertion_point(class_scope:nidevice_grpc.NIComplexNumberF32)
  })
_sym_db.RegisterMessage(NIComplexNumberF32)

NIComplexI16 = _reflection.GeneratedProtocolMessageType('NIComplexI16', (_message.Message,), {
  'DESCRIPTOR' : _NICOMPLEXI16,
  '__module__' : 'nidevice_pb2'
  # @@protoc_insertion_point(class_scope:nidevice_grpc.NIComplexI16)
  })
_sym_db.RegisterMessage(NIComplexI16)

SmtSpectrumInfo = _reflection.GeneratedProtocolMessageType('SmtSpectrumInfo', (_message.Message,), {
  'DESCRIPTOR' : _SMTSPECTRUMINFO,
  '__module__' : 'nidevice_pb2'
  # @@protoc_insertion_point(class_scope:nidevice_grpc.SmtSpectrumInfo)
  })
_sym_db.RegisterMessage(SmtSpectrumInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022com.ni.grpc.deviceB\010NiDeviceP\001\252\002\037NationalInstruments.Grpc.Device'
  _NICOMPLEXNUMBER._serialized_start=33
  _NICOMPLEXNUMBER._serialized_end=83
  _NICOMPLEXNUMBERF32._serialized_start=85
  _NICOMPLEXNUMBERF32._serialized_end=138
  _NICOMPLEXI16._serialized_start=140
  _NICOMPLEXI16._serialized_end=187
  _SMTSPECTRUMINFO._serialized_start=189
  _SMTSPECTRUMINFO._serialized_end=303
# @@protoc_insertion_point(module_scope)
